<?php

use Illuminate\Database\Seeder;
use App\State;

class StatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        State::create(['LGA' =>'Abadam','State' => 'Borno']);
State::create(['LGA' =>'Abaji','State' => 'FCT']);
State::create(['LGA' =>'Abak','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Abakaliki','State' => 'Ebonyi']);
State::create(['LGA' =>'Aba North','State' => 'Abia']);
State::create(['LGA' =>'Aba South','State' => 'Abia']);
State::create(['LGA' =>'Abeokuta North','State' => 'Ogun']);
State::create(['LGA' =>'Abeokuta South','State' => 'Ogun']);
State::create(['LGA' =>'Abi','State' => 'Cross River']);
State::create(['LGA' =>'Aboh Mbaise','State' => 'Imo']);
State::create(['LGA' =>'Abua/Odual','State' => 'Rivers']);
State::create(['LGA' =>'Adavi','State' => 'Kogi']);
State::create(['LGA' =>'Ado Ekiti','State' => 'Ekiti']);
State::create(['LGA' =>'Ado-Odo/Ota','State' => 'Ogun']);
State::create(['LGA' =>'Afijio','State' => 'Oyo']);
State::create(['LGA' =>'Afikpo North','State' => 'Ebonyi']);
State::create(['LGA' =>'Afikpo South (Edda)','State' => 'Ebonyi']);
State::create(['LGA' =>'Agaie','State' => 'Niger']);
State::create(['LGA' =>'Agatu','State' => 'Benue']);
State::create(['LGA' =>'Agwara','State' => 'Niger']);
State::create(['LGA' =>'Agege','State' => 'Lagos']);
State::create(['LGA' =>'Aguata','State' => 'Anambra']);
State::create(['LGA' =>'Ahiazu Mbaise','State' => 'Imo']);
State::create(['LGA' =>'Ahoada East','State' => 'Rivers']);
State::create(['LGA' =>'Ahoada West','State' => 'Rivers']);
State::create(['LGA' =>'Ajaokuta','State' => 'Kogi']);
State::create(['LGA' =>'Ajeromi-Ifelodun','State' => 'Lagos']);
State::create(['LGA' =>'Ajingi','State' => 'Kano']);
State::create(['LGA' =>'Akamkpa','State' => 'Cross River']);
State::create(['LGA' =>'Akinyele','State' => 'Oyo']);
State::create(['LGA' =>'Akko','State' => 'Gombe']);
State::create(['LGA' =>'Akoko-Edo','State' => 'Edo']);
State::create(['LGA' =>'Akoko North-East','State' => 'Ondo']);
State::create(['LGA' =>'Akoko North-West','State' => 'Ondo']);
State::create(['LGA' =>'Akoko South-West','State' => 'Ondo']);
State::create(['LGA' =>'Akoko South-East','State' => 'Ondo']);
State::create(['LGA' =>'Akpabuyo','State' => 'Cross River']);
State::create(['LGA' =>'Akuku-Toru','State' => 'Rivers']);
State::create(['LGA' =>'Akure North','State' => 'Ondo']);
State::create(['LGA' =>'Akure South','State' => 'Ondo']);
State::create(['LGA' =>'Akwanga','State' => 'Nasarawa']);
State::create(['LGA' =>'Albasu','State' => 'Kano']);
State::create(['LGA' =>'Aleiro','State' => 'Kebbi']);
State::create(['LGA' =>'Alimosho','State' => 'Lagos']);
State::create(['LGA' =>'Alkaleri','State' => 'Bauchi']);
State::create(['LGA' =>'Amuwo-Odofin','State' => 'Lagos']);
State::create(['LGA' =>'Anambra East','State' => 'Anambra']);
State::create(['LGA' =>'Anambra West','State' => 'Anambra']);
State::create(['LGA' =>'Anaocha','State' => 'Anambra']);
State::create(['LGA' =>'Andoni','State' => 'Rivers']);
State::create(['LGA' =>'Aninri','State' => 'Enugu']);
State::create(['LGA' =>'Aniocha North','State' => 'Delta']);
State::create(['LGA' =>'Aniocha South','State' => 'Delta']);
State::create(['LGA' =>'Anka','State' => 'Zamfara']);
State::create(['LGA' =>'Ankpa','State' => 'Kogi']);
State::create(['LGA' =>'Apa','State' => 'Benue']);
State::create(['LGA' =>'Apapa','State' => 'Lagos']);
State::create(['LGA' =>'Ado','State' => 'Benue']);
State::create(['LGA' =>'Ardo Kola','State' => 'Taraba']);
State::create(['LGA' =>'Arewa Dandi','State' => 'Kebbi']);
State::create(['LGA' =>'Argungu','State' => 'Kebbi']);
State::create(['LGA' =>'Arochukwu','State' => 'Abia']);
State::create(['LGA' =>'Asa','State' => 'Kwara']);
State::create(['LGA' =>'Asari-Toru','State' => 'Rivers']);
State::create(['LGA' =>'Askira/Uba','State' => 'Borno']);
State::create(['LGA' =>'Atakunmosa East','State' => 'Osun']);
State::create(['LGA' =>'Atakunmosa West','State' => 'Osun']);
State::create(['LGA' =>'Atiba','State' => 'Oyo']);
State::create(['LGA' =>'Atisbo','State' => 'Oyo']);
State::create(['LGA' =>'Augie','State' => 'Kebbi']);
State::create(['LGA' =>'Auyo','State' => 'Jigawa']);
State::create(['LGA' =>'Awe','State' => 'Nasarawa']);
State::create(['LGA' =>'Awgu','State' => 'Enugu']);
State::create(['LGA' =>'Awka North','State' => 'Anambra']);
State::create(['LGA' =>'Awka South','State' => 'Anambra']);
State::create(['LGA' =>'Ayamelum','State' => 'Anambra']);
State::create(['LGA' =>'Aiyedaade','State' => 'Osun']);
State::create(['LGA' =>'Aiyedire','State' => 'Osun']);
State::create(['LGA' =>'Babura','State' => 'Jigawa']);
State::create(['LGA' =>'Badagry','State' => 'Lagos']);
State::create(['LGA' =>'Bagudo','State' => 'Kebbi']);
State::create(['LGA' =>'Bagwai','State' => 'Kano']);
State::create(['LGA' =>'Bakassi','State' => 'Cross River']);
State::create(['LGA' =>'Bokkos','State' => 'Plateau']);
State::create(['LGA' =>'Bakori','State' => 'Katsina']);
State::create(['LGA' =>'Bakura','State' => 'Zamfara']);
State::create(['LGA' =>'Balanga','State' => 'Gombe']);
State::create(['LGA' =>'Bali','State' => 'Taraba']);
State::create(['LGA' =>'Bama','State' => 'Borno']);
State::create(['LGA' =>'Bade','State' => 'Yobe']);
State::create(['LGA' =>'Barkin Ladi','State' => 'Plateau']);
State::create(['LGA' =>'Baruten','State' => 'Kwara']);
State::create(['LGA' =>'Bassa','State' => 'Kogi']);
State::create(['LGA' =>'Bassa','State' => 'Plateau']);
State::create(['LGA' =>'Batagarawa','State' => 'Katsina']);
State::create(['LGA' =>'Batsari','State' => 'Katsina']);
State::create(['LGA' =>'Bauchi','State' => 'Bauchi']);
State::create(['LGA' =>'Baure','State' => 'Katsina']);
State::create(['LGA' =>'Bayo','State' => 'Borno']);
State::create(['LGA' =>'Bebeji','State' => 'Kano']);
State::create(['LGA' =>'Bekwarra','State' => 'Cross River']);
State::create(['LGA' =>'Bende','State' => 'Abia']);
State::create(['LGA' =>'Biase','State' => 'Cross River']);
State::create(['LGA' =>'Bichi','State' => 'Kano']);
State::create(['LGA' =>'Bida','State' => 'Niger']);
State::create(['LGA' =>'Billiri','State' => 'Gombe']);
State::create(['LGA' =>'Bindawa','State' => 'Katsina']);
State::create(['LGA' =>'Binji','State' => 'Sokoto']);
State::create(['LGA' =>'Biriniwa','State' => 'Jigawa']);
State::create(['LGA' =>'Birnin Gwari','State' => 'Kaduna']);
State::create(['LGA' =>'Birnin Kebbi','State' => 'Kebbi']);
State::create(['LGA' =>'Birnin Kudu','State' => 'Jigawa']);
State::create(['LGA' =>'Birnin Magaji/Kiyaw','State' => 'Zamfara']);
State::create(['LGA' =>'Biu','State' => 'Borno']);
State::create(['LGA' =>'Bodinga','State' => 'Sokoto']);
State::create(['LGA' =>'Bogoro','State' => 'Bauchi']);
State::create(['LGA' =>'Boki','State' => 'Cross River']);
State::create(['LGA' =>'Boluwaduro','State' => 'Osun']);
State::create(['LGA' =>'Bomadi','State' => 'Delta']);
State::create(['LGA' =>'Bonny','State' => 'Rivers']);
State::create(['LGA' =>'Borgu','State' => 'Niger']);
State::create(['LGA' =>'Boripe','State' => 'Osun']);
State::create(['LGA' =>'Bursari','State' => 'Yobe']);
State::create(['LGA' =>'Bosso','State' => 'Niger']);
State::create(['LGA' =>'Brass','State' => 'Bayelsa']);
State::create(['LGA' =>'Buji','State' => 'Jigawa']);
State::create(['LGA' =>'Bukkuyum','State' => 'Zamfara']);
State::create(['LGA' =>'Buruku','State' => 'Benue']);
State::create(['LGA' =>'Bungudu','State' => 'Zamfara']);
State::create(['LGA' =>'Bunkure','State' => 'Kano']);
State::create(['LGA' =>'Bunza','State' => 'Kebbi']);
State::create(['LGA' =>'Burutu','State' => 'Delta']);
State::create(['LGA' =>'Bwari','State' => 'FCT']);
State::create(['LGA' =>'Calabar Municipal','State' => 'Cross River']);
State::create(['LGA' =>'Calabar South','State' => 'Cross River']);
State::create(['LGA' =>'Chanchaga','State' => 'Niger']);
State::create(['LGA' =>'Charanchi','State' => 'Katsina']);
State::create(['LGA' =>'Chibok','State' => 'Borno']);
State::create(['LGA' =>'Chikun','State' => 'Kaduna']);
State::create(['LGA' =>'Dala','State' => 'Kano']);
State::create(['LGA' =>'Damaturu','State' => 'Yobe']);
State::create(['LGA' =>'Damban','State' => 'Bauchi']);
State::create(['LGA' =>'Dambatta','State' => 'Kano']);
State::create(['LGA' =>'Damboa','State' => 'Borno']);
State::create(['LGA' =>'Dandi','State' => 'Kebbi']);
State::create(['LGA' =>'Dandume','State' => 'Katsina']);
State::create(['LGA' =>'Dange Shuni','State' => 'Sokoto']);
State::create(['LGA' =>'Danja','State' => 'Katsina']);
State::create(['LGA' =>'Dan Musa','State' => 'Katsina']);
State::create(['LGA' =>'Darazo','State' => 'Bauchi']);
State::create(['LGA' =>'Dass','State' => 'Bauchi']);
State::create(['LGA' =>'Daura','State' => 'Katsina']);
State::create(['LGA' =>'Dawakin Kudu','State' => 'Kano']);
State::create(['LGA' =>'Dawakin Tofa','State' => 'Kano']);
State::create(['LGA' =>'Degema','State' => 'Rivers']);
State::create(['LGA' =>'Dekina','State' => 'Kogi']);
State::create(['LGA' =>'Demsa','State' => 'Adamawa']);
State::create(['LGA' =>'Dikwa','State' => 'Borno']);
State::create(['LGA' =>'Doguwa','State' => 'Kano']);
State::create(['LGA' =>'Doma','State' => 'Nasarawa']);
State::create(['LGA' =>'Donga','State' => 'Taraba']);
State::create(['LGA' =>'Dukku','State' => 'Gombe']);
State::create(['LGA' =>'Dunukofia','State' => 'Anambra']);
State::create(['LGA' =>'Dutse','State' => 'Jigawa']);
State::create(['LGA' =>'Dutsi','State' => 'Katsina']);
State::create(['LGA' =>'Dutsin Ma','State' => 'Katsina']);
State::create(['LGA' =>'Eastern Obolo','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ebonyi','State' => 'Ebonyi']);
State::create(['LGA' =>'Edati','State' => 'Niger']);
State::create(['LGA' =>'Ede North','State' => 'Osun']);
State::create(['LGA' =>'Ede South','State' => 'Osun']);
State::create(['LGA' =>'Edu','State' => 'Kwara']);
State::create(['LGA' =>'Ife Central','State' => 'Osun']);
State::create(['LGA' =>'Ife East','State' => 'Osun']);
State::create(['LGA' =>'Ife North','State' => 'Osun']);
State::create(['LGA' =>'Ife South','State' => 'Osun']);
State::create(['LGA' =>'Efon','State' => 'Ekiti']);
State::create(['LGA' =>'Egbado North','State' => 'Ogun']);
State::create(['LGA' =>'Egbado South','State' => 'Ogun']);
State::create(['LGA' =>'Egbeda','State' => 'Oyo']);
State::create(['LGA' =>'Egbedore','State' => 'Osun']);
State::create(['LGA' =>'Egor','State' => 'Edo']);
State::create(['LGA' =>'Ehime Mbano','State' => 'Imo']);
State::create(['LGA' =>'Ejigbo','State' => 'Osun']);
State::create(['LGA' =>'Ekeremor','State' => 'Bayelsa']);
State::create(['LGA' =>'Eket','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ekiti','State' => 'Kwara']);
State::create(['LGA' =>'Ekiti East','State' => 'Ekiti']);
State::create(['LGA' =>'Ekiti South-West','State' => 'Ekiti']);
State::create(['LGA' =>'Ekiti West','State' => 'Ekiti']);
State::create(['LGA' =>'Ekwusigo','State' => 'Anambra']);
State::create(['LGA' =>'Eleme','State' => 'Rivers']);
State::create(['LGA' =>'Emuoha','State' => 'Rivers']);
State::create(['LGA' =>'Emure','State' => 'Ekiti']);
State::create(['LGA' =>'Enugu East','State' => 'Enugu']);
State::create(['LGA' =>'Enugu North','State' => 'Enugu']);
State::create(['LGA' =>'Enugu South','State' => 'Enugu']);
State::create(['LGA' =>'Epe','State' => 'Lagos']);
State::create(['LGA' =>'Esan Central','State' => 'Edo']);
State::create(['LGA' =>'Esan North-East','State' => 'Edo']);
State::create(['LGA' =>'Esan South-East','State' => 'Edo']);
State::create(['LGA' =>'Esan West','State' => 'Edo']);
State::create(['LGA' =>'Ese Odo','State' => 'Ondo']);
State::create(['LGA' =>'Esit Eket','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Essien Udim','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Etche','State' => 'Rivers']);
State::create(['LGA' =>'Ethiope East','State' => 'Delta']);
State::create(['LGA' =>'Ethiope West','State' => 'Delta']);
State::create(['LGA' =>'Etim Ekpo','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Etinan','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Eti Osa','State' => 'Lagos']);
State::create(['LGA' =>'Etsako Central','State' => 'Edo']);
State::create(['LGA' =>'Etsako East','State' => 'Edo']);
State::create(['LGA' =>'Etsako West','State' => 'Edo']);
State::create(['LGA' =>'Etung','State' => 'Cross River']);
State::create(['LGA' =>'Ewekoro','State' => 'Ogun']);
State::create(['LGA' =>'Ezeagu','State' => 'Enugu']);
State::create(['LGA' =>'Ezinihitte','State' => 'Imo']);
State::create(['LGA' =>'Ezza North','State' => 'Ebonyi']);
State::create(['LGA' =>'Ezza South','State' => 'Ebonyi']);
State::create(['LGA' =>'Fagge','State' => 'Kano']);
State::create(['LGA' =>'Fakai','State' => 'Kebbi']);
State::create(['LGA' =>'Faskari','State' => 'Katsina']);
State::create(['LGA' =>'Fika','State' => 'Yobe']);
State::create(['LGA' =>'Fufure','State' => 'Adamawa']);
State::create(['LGA' =>'Funakaye','State' => 'Gombe']);
State::create(['LGA' =>'Fune','State' => 'Yobe']);
State::create(['LGA' =>'Funtua','State' => 'Katsina']);
State::create(['LGA' =>'Gabasawa','State' => 'Kano']);
State::create(['LGA' =>'Gada','State' => 'Sokoto']);
State::create(['LGA' =>'Gagarawa','State' => 'Jigawa']);
State::create(['LGA' =>'Gamawa','State' => 'Bauchi']);
State::create(['LGA' =>'Ganjuwa','State' => 'Bauchi']);
State::create(['LGA' =>'Ganye','State' => 'Adamawa']);
State::create(['LGA' =>'Garki','State' => 'Jigawa']);
State::create(['LGA' =>'Garko','State' => 'Kano']);
State::create(['LGA' =>'Garun Mallam','State' => 'Kano']);
State::create(['LGA' =>'Gashaka','State' => 'Taraba']);
State::create(['LGA' =>'Gassol','State' => 'Taraba']);
State::create(['LGA' =>'Gaya','State' => 'Kano']);
State::create(['LGA' =>'Gayuk','State' => 'Adamawa']);
State::create(['LGA' =>'Gezawa','State' => 'Kano']);
State::create(['LGA' =>'Gbako','State' => 'Niger']);
State::create(['LGA' =>'Gboko','State' => 'Benue']);
State::create(['LGA' =>'Gbonyin','State' => 'Ekiti']);
State::create(['LGA' =>'Geidam','State' => 'Yobe']);
State::create(['LGA' =>'Giade','State' => 'Bauchi']);
State::create(['LGA' =>'Giwa','State' => 'Kaduna']);
State::create(['LGA' =>'Gokana','State' => 'Rivers']);
State::create(['LGA' =>'Gombe','State' => 'Gombe']);
State::create(['LGA' =>'Gombi','State' => 'Adamawa']);
State::create(['LGA' =>'Goronyo','State' => 'Sokoto']);
State::create(['LGA' =>'Grie','State' => 'Adamawa']);
State::create(['LGA' =>'Gubio','State' => 'Borno']);
State::create(['LGA' =>'Gudu','State' => 'Sokoto']);
State::create(['LGA' =>'Gujba','State' => 'Yobe']);
State::create(['LGA' =>'Gulani','State' => 'Yobe']);
State::create(['LGA' =>'Guma','State' => 'Benue']);
State::create(['LGA' =>'Gumel','State' => 'Jigawa']);
State::create(['LGA' =>'Gummi','State' => 'Zamfara']);
State::create(['LGA' =>'Gurara','State' => 'Niger']);
State::create(['LGA' =>'Guri','State' => 'Jigawa']);
State::create(['LGA' =>'Gusau','State' => 'Zamfara']);
State::create(['LGA' =>'Guzamala','State' => 'Borno']);
State::create(['LGA' =>'Gwadabawa','State' => 'Sokoto']);
State::create(['LGA' =>'Gwagwalada','State' => 'FCT']);
State::create(['LGA' =>'Gwale','State' => 'Kano']);
State::create(['LGA' =>'Gwandu','State' => 'Kebbi']);
State::create(['LGA' =>'Gwaram','State' => 'Jigawa']);
State::create(['LGA' =>'Gwarzo','State' => 'Kano']);
State::create(['LGA' =>'Gwer East','State' => 'Benue']);
State::create(['LGA' =>'Gwer West','State' => 'Benue']);
State::create(['LGA' =>'Gwiwa','State' => 'Jigawa']);
State::create(['LGA' =>'Gwoza','State' => 'Borno']);
State::create(['LGA' =>'Hadejia','State' => 'Jigawa']);
State::create(['LGA' =>'Hawul','State' => 'Borno']);
State::create(['LGA' =>'Hong','State' => 'Adamawa']);
State::create(['LGA' =>'Ibadan North','State' => 'Oyo']);
State::create(['LGA' =>'Ibadan North-East','State' => 'Oyo']);
State::create(['LGA' =>'Ibadan North-West','State' => 'Oyo']);
State::create(['LGA' =>'Ibadan South-East','State' => 'Oyo']);
State::create(['LGA' =>'Ibadan South-West','State' => 'Oyo']);
State::create(['LGA' =>'Ibaji','State' => 'Kogi']);
State::create(['LGA' =>'Ibarapa Central','State' => 'Oyo']);
State::create(['LGA' =>'Ibarapa East','State' => 'Oyo']);
State::create(['LGA' =>'Ibarapa North','State' => 'Oyo']);
State::create(['LGA' =>'Ibeju-Lekki','State' => 'Lagos']);
State::create(['LGA' =>'Ibeno','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ibesikpo Asutan','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ibi','State' => 'Taraba']);
State::create(['LGA' =>'Ibiono-Ibom','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Idah','State' => 'Kogi']);
State::create(['LGA' =>'Idanre','State' => 'Ondo']);
State::create(['LGA' =>'Ideato North','State' => 'Imo']);
State::create(['LGA' =>'Ideato South','State' => 'Imo']);
State::create(['LGA' =>'Idemili North','State' => 'Anambra']);
State::create(['LGA' =>'Idemili South','State' => 'Anambra']);
State::create(['LGA' =>'Ido','State' => 'Oyo']);
State::create(['LGA' =>'Ido Osi','State' => 'Ekiti']);
State::create(['LGA' =>'Ifako-Ijaiye','State' => 'Lagos']);
State::create(['LGA' =>'Ifedayo','State' => 'Osun']);
State::create(['LGA' =>'Ifedore','State' => 'Ondo']);
State::create(['LGA' =>'Ifelodun','State' => 'Kwara']);
State::create(['LGA' =>'Ifelodun','State' => 'Osun']);
State::create(['LGA' =>'Ifo','State' => 'Ogun']);
State::create(['LGA' =>'Igabi','State' => 'Kaduna']);
State::create(['LGA' =>'Igalamela Odolu','State' => 'Kogi']);
State::create(['LGA' =>'Igbo Etiti','State' => 'Enugu']);
State::create(['LGA' =>'Igbo Eze North','State' => 'Enugu']);
State::create(['LGA' =>'Igbo Eze South','State' => 'Enugu']);
State::create(['LGA' =>'Igueben','State' => 'Edo']);
State::create(['LGA' =>'Ihiala','State' => 'Anambra']);
State::create(['LGA' =>'Ihitte/Uboma','State' => 'Imo']);
State::create(['LGA' =>'Ilaje','State' => 'Ondo']);
State::create(['LGA' =>'Ijebu East','State' => 'Ogun']);
State::create(['LGA' =>'Ijebu North','State' => 'Ogun']);
State::create(['LGA' =>'Ijebu North East','State' => 'Ogun']);
State::create(['LGA' =>'Ijebu Ode','State' => 'Ogun']);
State::create(['LGA' =>'Ijero','State' => 'Ekiti']);
State::create(['LGA' =>'Ijumu','State' => 'Kogi']);
State::create(['LGA' =>'Ika','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ika North East','State' => 'Delta']);
State::create(['LGA' =>'Ikara','State' => 'Kaduna']);
State::create(['LGA' =>'Ika South','State' => 'Delta']);
State::create(['LGA' =>'Ikeduru','State' => 'Imo']);
State::create(['LGA' =>'Ikeja','State' => 'Lagos']);
State::create(['LGA' =>'Ikenne','State' => 'Ogun']);
State::create(['LGA' =>'Ikere','State' => 'Ekiti']);
State::create(['LGA' =>'Ikole','State' => 'Ekiti']);
State::create(['LGA' =>'Ikom','State' => 'Cross River']);
State::create(['LGA' =>'Ikono','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ikorodu','State' => 'Lagos']);
State::create(['LGA' =>'Ikot Abasi','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ikot Ekpene','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ikpoba Okha','State' => 'Edo']);
State::create(['LGA' =>'Ikwerre','State' => 'Rivers']);
State::create(['LGA' =>'Ikwo','State' => 'Ebonyi']);
State::create(['LGA' =>'Ikwuano','State' => 'Abia']);
State::create(['LGA' =>'Ila','State' => 'Osun']);
State::create(['LGA' =>'Ilejemeje','State' => 'Ekiti']);
State::create(['LGA' =>'Ile Oluji/Okeigbo','State' => 'Ondo']);
State::create(['LGA' =>'Ilesa East','State' => 'Osun']);
State::create(['LGA' =>'Ilesa West','State' => 'Osun']);
State::create(['LGA' =>'Illela','State' => 'Sokoto']);
State::create(['LGA' =>'Ilorin East','State' => 'Kwara']);
State::create(['LGA' =>'Ilorin South','State' => 'Kwara']);
State::create(['LGA' =>'Ilorin West','State' => 'Kwara']);
State::create(['LGA' =>'Imeko Afon','State' => 'Ogun']);
State::create(['LGA' =>'Ingawa','State' => 'Katsina']);
State::create(['LGA' =>'Ini','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ipokia','State' => 'Ogun']);
State::create(['LGA' =>'Irele','State' => 'Ondo']);
State::create(['LGA' =>'Irepo','State' => 'Oyo']);
State::create(['LGA' =>'Irepodun','State' => 'Kwara']);
State::create(['LGA' =>'Irepodun','State' => 'Osun']);
State::create(['LGA' =>'Irepodun/Ifelodun','State' => 'Ekiti']);
State::create(['LGA' =>'Irewole','State' => 'Osun']);
State::create(['LGA' =>'Isa','State' => 'Sokoto']);
State::create(['LGA' =>'Ise/Orun','State' => 'Ekiti']);
State::create(['LGA' =>'Iseyin','State' => 'Oyo']);
State::create(['LGA' =>'Ishielu','State' => 'Ebonyi']);
State::create(['LGA' =>'Isiala Mbano','State' => 'Imo']);
State::create(['LGA' =>'Isiala Ngwa North','State' => 'Abia']);
State::create(['LGA' =>'Isiala Ngwa South','State' => 'Abia']);
State::create(['LGA' =>'Isin','State' => 'Kwara']);
State::create(['LGA' =>'Isi Uzo','State' => 'Enugu']);
State::create(['LGA' =>'Isokan','State' => 'Osun']);
State::create(['LGA' =>'Isoko North','State' => 'Delta']);
State::create(['LGA' =>'Isoko South','State' => 'Delta']);
State::create(['LGA' =>'Isu','State' => 'Imo']);
State::create(['LGA' =>'Isuikwuato','State' => 'Abia']);
State::create(['LGA' =>'Itas/Gadau','State' => 'Bauchi']);
State::create(['LGA' =>'Itesiwaju','State' => 'Oyo']);
State::create(['LGA' =>'Itu','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ivo','State' => 'Ebonyi']);
State::create(['LGA' =>'Iwajowa','State' => 'Oyo']);
State::create(['LGA' =>'Iwo','State' => 'Osun']);
State::create(['LGA' =>'Izzi','State' => 'Ebonyi']);
State::create(['LGA' =>'Jaba','State' => 'Kaduna']);
State::create(['LGA' =>'Jada','State' => 'Adamawa']);
State::create(['LGA' =>'Jahun','State' => 'Jigawa']);
State::create(['LGA' =>'Jakusko','State' => 'Yobe']);
State::create(['LGA' =>'Jalingo','State' => 'Taraba']);
State::create(['LGA' =>'Jamaare','State' => 'Bauchi']);
State::create(['LGA' =>'Jega','State' => 'Kebbi']);
State::create(['LGA' =>'Jemaa','State' => 'Kaduna']);
State::create(['LGA' =>'Jere','State' => 'Borno']);
State::create(['LGA' =>'Jibia','State' => 'Katsina']);
State::create(['LGA' =>'Jos East','State' => 'Plateau']);
State::create(['LGA' =>'Jos North','State' => 'Plateau']);
State::create(['LGA' =>'Jos South','State' => 'Plateau']);
State::create(['LGA' =>'Kabba/Bunu','State' => 'Kogi']);
State::create(['LGA' =>'Kabo','State' => 'Kano']);
State::create(['LGA' =>'Kachia','State' => 'Kaduna']);
State::create(['LGA' =>'Kaduna North','State' => 'Kaduna']);
State::create(['LGA' =>'Kaduna South','State' => 'Kaduna']);
State::create(['LGA' =>'Kafin Hausa','State' => 'Jigawa']);
State::create(['LGA' =>'Kafur','State' => 'Katsina']);
State::create(['LGA' =>'Kaga','State' => 'Borno']);
State::create(['LGA' =>'Kagarko','State' => 'Kaduna']);
State::create(['LGA' =>'Kaiama','State' => 'Kwara']);
State::create(['LGA' =>'Kaita','State' => 'Katsina']);
State::create(['LGA' =>'Kajola','State' => 'Oyo']);
State::create(['LGA' =>'Kajuru','State' => 'Kaduna']);
State::create(['LGA' =>'Kala/Balge','State' => 'Borno']);
State::create(['LGA' =>'Kalgo','State' => 'Kebbi']);
State::create(['LGA' =>'Kaltungo','State' => 'Gombe']);
State::create(['LGA' =>'Kanam','State' => 'Plateau']);
State::create(['LGA' =>'Kankara','State' => 'Katsina']);
State::create(['LGA' =>'Kanke','State' => 'Plateau']);
State::create(['LGA' =>'Kankia','State' => 'Katsina']);
State::create(['LGA' =>'Kano Municipal','State' => 'Kano']);
State::create(['LGA' =>'Karasuwa','State' => 'Yobe']);
State::create(['LGA' =>'Karaye','State' => 'Kano']);
State::create(['LGA' =>'Karim Lamido','State' => 'Taraba']);
State::create(['LGA' =>'Karu','State' => 'Nasarawa']);
State::create(['LGA' =>'Katagum','State' => 'Bauchi']);
State::create(['LGA' =>'Katcha','State' => 'Niger']);
State::create(['LGA' =>'Katsina','State' => 'Katsina']);
State::create(['LGA' =>'Katsina-Ala','State' => 'Benue']);
State::create(['LGA' =>'Kaura','State' => 'Kaduna']);
State::create(['LGA' =>'Kaura Namoda','State' => 'Zamfara']);
State::create(['LGA' =>'Kauru','State' => 'Kaduna']);
State::create(['LGA' =>'Kazaure','State' => 'Jigawa']);
State::create(['LGA' =>'Keana','State' => 'Nasarawa']);
State::create(['LGA' =>'Kebbe','State' => 'Sokoto']);
State::create(['LGA' =>'Keffi','State' => 'Nasarawa']);
State::create(['LGA' =>'Khana','State' => 'Rivers']);
State::create(['LGA' =>'Kibiya','State' => 'Kano']);
State::create(['LGA' =>'Kirfi','State' => 'Bauchi']);
State::create(['LGA' =>'Kiri Kasama','State' => 'Jigawa']);
State::create(['LGA' =>'Kiru','State' => 'Kano']);
State::create(['LGA' =>'Kiyawa','State' => 'Jigawa']);
State::create(['LGA' =>'Kogi','State' => 'Kogi']);
State::create(['LGA' =>'Koko/Besse','State' => 'Kebbi']);
State::create(['LGA' =>'Kokona','State' => 'Nasarawa']);
State::create(['LGA' =>'Kolokuma/Opokuma','State' => 'Bayelsa']);
State::create(['LGA' =>'Konduga','State' => 'Borno']);
State::create(['LGA' =>'Konshisha','State' => 'Benue']);
State::create(['LGA' =>'Kontagora','State' => 'Niger']);
State::create(['LGA' =>'Kosofe','State' => 'Lagos']);
State::create(['LGA' =>'Kaugama','State' => 'Jigawa']);
State::create(['LGA' =>'Kubau','State' => 'Kaduna']);
State::create(['LGA' =>'Kudan','State' => 'Kaduna']);
State::create(['LGA' =>'Kuje','State' => 'FCT']);
State::create(['LGA' =>'Kukawa','State' => 'Borno']);
State::create(['LGA' =>'Kumbotso','State' => 'Kano']);
State::create(['LGA' =>'Kumi','State' => 'Taraba']);
State::create(['LGA' =>'Kunchi','State' => 'Kano']);
State::create(['LGA' =>'Kura','State' => 'Kano']);
State::create(['LGA' =>'Kurfi','State' => 'Katsina']);
State::create(['LGA' =>'Kusada','State' => 'Katsina']);
State::create(['LGA' =>'Kwali','State' => 'FCT']);
State::create(['LGA' =>'Kwande','State' => 'Benue']);
State::create(['LGA' =>'Kwami','State' => 'Gombe']);
State::create(['LGA' =>'Kware','State' => 'Sokoto']);
State::create(['LGA' =>'Kwaya Kusar','State' => 'Borno']);
State::create(['LGA' =>'Lafia','State' => 'Nasarawa']);
State::create(['LGA' =>'Lagelu','State' => 'Oyo']);
State::create(['LGA' =>'Lagos Island','State' => 'Lagos']);
State::create(['LGA' =>'Lagos Mainland','State' => 'Lagos']);
State::create(['LGA' =>'Langtang South','State' => 'Plateau']);
State::create(['LGA' =>'Langtang North','State' => 'Plateau']);
State::create(['LGA' =>'Lapai','State' => 'Niger']);
State::create(['LGA' =>'Lamurde','State' => 'Adamawa']);
State::create(['LGA' =>'Lau','State' => 'Taraba']);
State::create(['LGA' =>'Lavun','State' => 'Niger']);
State::create(['LGA' =>'Lere','State' => 'Kaduna']);
State::create(['LGA' =>'Logo','State' => 'Benue']);
State::create(['LGA' =>'Lokoja','State' => 'Kogi']);
State::create(['LGA' =>'Machina','State' => 'Yobe']);
State::create(['LGA' =>'Madagali','State' => 'Adamawa']);
State::create(['LGA' =>'Madobi','State' => 'Kano']);
State::create(['LGA' =>'Mafa','State' => 'Borno']);
State::create(['LGA' =>'Magama','State' => 'Niger']);
State::create(['LGA' =>'Magumeri','State' => 'Borno']);
State::create(['LGA' =>'MaiAdua','State' => 'Katsina']);
State::create(['LGA' =>'Maiduguri','State' => 'Borno']);
State::create(['LGA' =>'Maigatari','State' => 'Jigawa']);
State::create(['LGA' =>'Maiha','State' => 'Adamawa']);
State::create(['LGA' =>'Maiyama','State' => 'Kebbi']);
State::create(['LGA' =>'Makarfi','State' => 'Kaduna']);
State::create(['LGA' =>'Makoda','State' => 'Kano']);
State::create(['LGA' =>'Malam Madori','State' => 'Jigawa']);
State::create(['LGA' =>'Malumfashi','State' => 'Katsina']);
State::create(['LGA' =>'Mangu','State' => 'Plateau']);
State::create(['LGA' =>'Mani','State' => 'Katsina']);
State::create(['LGA' =>'Maradun','State' => 'Zamfara']);
State::create(['LGA' =>'Mariga','State' => 'Niger']);
State::create(['LGA' =>'Makurdi','State' => 'Benue']);
State::create(['LGA' =>'Marte','State' => 'Borno']);
State::create(['LGA' =>'Maru','State' => 'Zamfara']);
State::create(['LGA' =>'Mashegu','State' => 'Niger']);
State::create(['LGA' =>'Mashi','State' => 'Katsina']);
State::create(['LGA' =>'Matazu','State' => 'Katsina']);
State::create(['LGA' =>'Mayo Belwa','State' => 'Adamawa']);
State::create(['LGA' =>'Mbaitoli','State' => 'Imo']);
State::create(['LGA' =>'Mbo','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Michika','State' => 'Adamawa']);
State::create(['LGA' =>'Miga','State' => 'Jigawa']);
State::create(['LGA' =>'Mikang','State' => 'Plateau']);
State::create(['LGA' =>'Minjibir','State' => 'Kano']);
State::create(['LGA' =>'Misau','State' => 'Bauchi']);
State::create(['LGA' =>'Moba','State' => 'Ekiti']);
State::create(['LGA' =>'Mobbar','State' => 'Borno']);
State::create(['LGA' =>'Mubi North','State' => 'Adamawa']);
State::create(['LGA' =>'Mubi South','State' => 'Adamawa']);
State::create(['LGA' =>'Mokwa','State' => 'Niger']);
State::create(['LGA' =>'Monguno','State' => 'Borno']);
State::create(['LGA' =>'Mopa Muro','State' => 'Kogi']);
State::create(['LGA' =>'Moro','State' => 'Kwara']);
State::create(['LGA' =>'Moya','State' => 'Niger']);
State::create(['LGA' =>'Mkpat-Enin','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Municipal Area Council','State' => 'FCT']);
State::create(['LGA' =>'Musawa','State' => 'Katsina']);
State::create(['LGA' =>'Mushin','State' => 'Lagos']);
State::create(['LGA' =>'Nafada','State' => 'Gombe']);
State::create(['LGA' =>'Nangere','State' => 'Yobe']);
State::create(['LGA' =>'Nasarawa','State' => 'Kano']);
State::create(['LGA' =>'Nasarawa','State' => 'Nasarawa']);
State::create(['LGA' =>'Nasarawa Egon','State' => 'Nasarawa']);
State::create(['LGA' =>'Ndokwa East','State' => 'Delta']);
State::create(['LGA' =>'Ndokwa West','State' => 'Delta']);
State::create(['LGA' =>'Nembe','State' => 'Bayelsa']);
State::create(['LGA' =>'Ngala','State' => 'Borno']);
State::create(['LGA' =>'Nganzai','State' => 'Borno']);
State::create(['LGA' =>'Ngaski','State' => 'Kebbi']);
State::create(['LGA' =>'Ngor Okpala','State' => 'Imo']);
State::create(['LGA' =>'Nguru','State' => 'Yobe']);
State::create(['LGA' =>'Ningi','State' => 'Bauchi']);
State::create(['LGA' =>'Njaba','State' => 'Imo']);
State::create(['LGA' =>'Njikoka','State' => 'Anambra']);
State::create(['LGA' =>'Nkanu East','State' => 'Enugu']);
State::create(['LGA' =>'Nkanu West','State' => 'Enugu']);
State::create(['LGA' =>'Nkwerre','State' => 'Imo']);
State::create(['LGA' =>'Nnewi North','State' => 'Anambra']);
State::create(['LGA' =>'Nnewi South','State' => 'Anambra']);
State::create(['LGA' =>'Nsit-Atai','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Nsit-Ibom','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Nsit-Ubium','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Nsukka','State' => 'Enugu']);
State::create(['LGA' =>'Numan','State' => 'Adamawa']);
State::create(['LGA' =>'Nwangele','State' => 'Imo']);
State::create(['LGA' =>'Obafemi Owode','State' => 'Ogun']);
State::create(['LGA' =>'Obanliku','State' => 'Cross River']);
State::create(['LGA' =>'Obi','State' => 'Benue']);
State::create(['LGA' =>'Obi','State' => 'Nasarawa']);
State::create(['LGA' =>'Obi Ngwa','State' => 'Abia']);
State::create(['LGA' =>'Obio/Akpor','State' => 'Rivers']);
State::create(['LGA' =>'Obokun','State' => 'Osun']);
State::create(['LGA' =>'Obot Akara','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Obowo','State' => 'Imo']);
State::create(['LGA' =>'Obubra','State' => 'Cross River']);
State::create(['LGA' =>'Obudu','State' => 'Cross River']);
State::create(['LGA' =>'Odeda','State' => 'Ogun']);
State::create(['LGA' =>'Odigbo','State' => 'Ondo']);
State::create(['LGA' =>'Odogbolu','State' => 'Ogun']);
State::create(['LGA' =>'Odo Otin','State' => 'Osun']);
State::create(['LGA' =>'Odukpani','State' => 'Cross River']);
State::create(['LGA' =>'Offa','State' => 'Kwara']);
State::create(['LGA' =>'Ofu','State' => 'Kogi']);
State::create(['LGA' =>'Ogba/Egbema/Ndoni','State' => 'Rivers']);
State::create(['LGA' =>'Ogbadibo','State' => 'Benue']);
State::create(['LGA' =>'Ogbaru','State' => 'Anambra']);
State::create(['LGA' =>'Ogbia','State' => 'Bayelsa']);
State::create(['LGA' =>'Ogbomosho North','State' => 'Oyo']);
State::create(['LGA' =>'Ogbomosho South','State' => 'Oyo']);
State::create(['LGA' =>'Ogu/Bolo','State' => 'Rivers']);
State::create(['LGA' =>'Ogoja','State' => 'Cross River']);
State::create(['LGA' =>'Ogo Oluwa','State' => 'Oyo']);
State::create(['LGA' =>'Ogori/Magongo','State' => 'Kogi']);
State::create(['LGA' =>'Ogun Waterside','State' => 'Ogun']);
State::create(['LGA' =>'Oguta','State' => 'Imo']);
State::create(['LGA' =>'Ohafia','State' => 'Abia']);
State::create(['LGA' =>'Ohaji/Egbema','State' => 'Imo']);
State::create(['LGA' =>'Ohaozara','State' => 'Ebonyi']);
State::create(['LGA' =>'Ohaukwu','State' => 'Ebonyi']);
State::create(['LGA' =>'Ohimini','State' => 'Benue']);
State::create(['LGA' =>'Orhionmwon','State' => 'Edo']);
State::create(['LGA' =>'Oji River','State' => 'Enugu']);
State::create(['LGA' =>'Ojo','State' => 'Lagos']);
State::create(['LGA' =>'Oju','State' => 'Benue']);
State::create(['LGA' =>'Okehi','State' => 'Kogi']);
State::create(['LGA' =>'Okene','State' => 'Kogi']);
State::create(['LGA' =>'Oke Ero','State' => 'Kwara']);
State::create(['LGA' =>'Okigwe','State' => 'Imo']);
State::create(['LGA' =>'Okitipupa','State' => 'Ondo']);
State::create(['LGA' =>'Okobo','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Okpe','State' => 'Delta']);
State::create(['LGA' =>'Okrika','State' => 'Rivers']);
State::create(['LGA' =>'Olamaboro','State' => 'Kogi']);
State::create(['LGA' =>'Ola Oluwa','State' => 'Osun']);
State::create(['LGA' =>'Olorunda','State' => 'Osun']);
State::create(['LGA' =>'Olorunsogo','State' => 'Oyo']);
State::create(['LGA' =>'Oluyole','State' => 'Oyo']);
State::create(['LGA' =>'Omala','State' => 'Kogi']);
State::create(['LGA' =>'Omuma','State' => 'Rivers']);
State::create(['LGA' =>'Ona Ara','State' => 'Oyo']);
State::create(['LGA' =>'Ondo East','State' => 'Ondo']);
State::create(['LGA' =>'Ondo West','State' => 'Ondo']);
State::create(['LGA' =>'Onicha','State' => 'Ebonyi']);
State::create(['LGA' =>'Onitsha North','State' => 'Anambra']);
State::create(['LGA' =>'Onitsha South','State' => 'Anambra']);
State::create(['LGA' =>'Onna','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Okpokwu','State' => 'Benue']);
State::create(['LGA' =>'Opobo/Nkoro','State' => 'Rivers']);
State::create(['LGA' =>'Oredo','State' => 'Edo']);
State::create(['LGA' =>'Orelope','State' => 'Oyo']);
State::create(['LGA' =>'Oriade','State' => 'Osun']);
State::create(['LGA' =>'Ori Ire','State' => 'Oyo']);
State::create(['LGA' =>'Orlu','State' => 'Imo']);
State::create(['LGA' =>'Orolu','State' => 'Osun']);
State::create(['LGA' =>'Oron','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Orsu','State' => 'Imo']);
State::create(['LGA' =>'Oru East','State' => 'Imo']);
State::create(['LGA' =>'Oruk Anam','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Orumba North','State' => 'Anambra']);
State::create(['LGA' =>'Orumba South','State' => 'Anambra']);
State::create(['LGA' =>'Oru West','State' => 'Imo']);
State::create(['LGA' =>'Ose','State' => 'Ondo']);
State::create(['LGA' =>'Oshimili North','State' => 'Delta']);
State::create(['LGA' =>'Oshimili South','State' => 'Delta']);
State::create(['LGA' =>'Oshodi-Isolo','State' => 'Lagos']);
State::create(['LGA' =>'Osisioma','State' => 'Abia']);
State::create(['LGA' =>'Osogbo','State' => 'Osun']);
State::create(['LGA' =>'Oturkpo','State' => 'Benue']);
State::create(['LGA' =>'Ovia North-East','State' => 'Edo']);
State::create(['LGA' =>'Ovia South-West','State' => 'Edo']);
State::create(['LGA' =>'Owan East','State' => 'Edo']);
State::create(['LGA' =>'Owan West','State' => 'Edo']);
State::create(['LGA' =>'Owerri Municipal','State' => 'Imo']);
State::create(['LGA' =>'Owerri North','State' => 'Imo']);
State::create(['LGA' =>'Owerri West','State' => 'Imo']);
State::create(['LGA' =>'Owo','State' => 'Ondo']);
State::create(['LGA' =>'Oye','State' => 'Ekiti']);
State::create(['LGA' =>'Oyi','State' => 'Anambra']);
State::create(['LGA' =>'Oyigbo','State' => 'Rivers']);
State::create(['LGA' =>'Oyo','State' => 'Oyo']);
State::create(['LGA' =>'Oyo East','State' => 'Oyo']);
State::create(['LGA' =>'Oyun','State' => 'Kwara']);
State::create(['LGA' =>'Paikoro','State' => 'Niger']);
State::create(['LGA' =>'Pankshin','State' => 'Plateau']);
State::create(['LGA' =>'Patani','State' => 'Delta']);
State::create(['LGA' =>'Pategi','State' => 'Kwara']);
State::create(['LGA' =>'Port Harcourt','State' => 'Rivers']);
State::create(['LGA' =>'Potiskum','State' => 'Yobe']);
State::create(['LGA' =>'Quaan Pan','State' => 'Plateau']);
State::create(['LGA' =>'Rabah','State' => 'Sokoto']);
State::create(['LGA' =>'Rafi','State' => 'Niger']);
State::create(['LGA' =>'Rano','State' => 'Kano']);
State::create(['LGA' =>'Remo North','State' => 'Ogun']);
State::create(['LGA' =>'Rijau','State' => 'Niger']);
State::create(['LGA' =>'Rimi','State' => 'Katsina']);
State::create(['LGA' =>'Rimin Gado','State' => 'Kano']);
State::create(['LGA' =>'Ringim','State' => 'Jigawa']);
State::create(['LGA' =>'Riyom','State' => 'Plateau']);
State::create(['LGA' =>'Rogo','State' => 'Kano']);
State::create(['LGA' =>'Roni','State' => 'Jigawa']);
State::create(['LGA' =>'Sabon Birni','State' => 'Sokoto']);
State::create(['LGA' =>'Sabon Gari','State' => 'Kaduna']);
State::create(['LGA' =>'Sabuwa','State' => 'Katsina']);
State::create(['LGA' =>'Safana','State' => 'Katsina']);
State::create(['LGA' =>'Sagbama','State' => 'Bayelsa']);
State::create(['LGA' =>'Sakaba','State' => 'Kebbi']);
State::create(['LGA' =>'Saki East','State' => 'Oyo']);
State::create(['LGA' =>'Saki West','State' => 'Oyo']);
State::create(['LGA' =>'Sandamu','State' => 'Katsina']);
State::create(['LGA' =>'Sanga','State' => 'Kaduna']);
State::create(['LGA' =>'Sapele','State' => 'Delta']);
State::create(['LGA' =>'Sardauna','State' => 'Taraba']);
State::create(['LGA' =>'Shagamu','State' => 'Ogun']);
State::create(['LGA' =>'Shagari','State' => 'Sokoto']);
State::create(['LGA' =>'Shanga','State' => 'Kebbi']);
State::create(['LGA' =>'Shani','State' => 'Borno']);
State::create(['LGA' =>'Shanono','State' => 'Kano']);
State::create(['LGA' =>'Shelleng','State' => 'Adamawa']);
State::create(['LGA' =>'Shendam','State' => 'Plateau']);
State::create(['LGA' =>'Shinkafi','State' => 'Zamfara']);
State::create(['LGA' =>'Shira','State' => 'Bauchi']);
State::create(['LGA' =>'Shiroro','State' => 'Niger']);
State::create(['LGA' =>'Shongom','State' => 'Gombe']);
State::create(['LGA' =>'Shomolu','State' => 'Lagos']);
State::create(['LGA' =>'Silame','State' => 'Sokoto']);
State::create(['LGA' =>'Soba','State' => 'Kaduna']);
State::create(['LGA' =>'Sokoto North','State' => 'Sokoto']);
State::create(['LGA' =>'Sokoto South','State' => 'Sokoto']);
State::create(['LGA' =>'Song','State' => 'Adamawa']);
State::create(['LGA' =>'Southern Ijaw','State' => 'Bayelsa']);
State::create(['LGA' =>'Suleja','State' => 'Niger']);
State::create(['LGA' =>'Sule Tankarkar','State' => 'Jigawa']);
State::create(['LGA' =>'Sumaila','State' => 'Kano']);
State::create(['LGA' =>'Suru','State' => 'Kebbi']);
State::create(['LGA' =>'Surulere','State' => 'Oyo']);
State::create(['LGA' =>'Surulere','State' => 'Lagos']);
State::create(['LGA' =>'Tafa','State' => 'Niger']);
State::create(['LGA' =>'Tafawa Balewa','State' => 'Bauchi']);
State::create(['LGA' =>'Tai','State' => 'Rivers']);
State::create(['LGA' =>'Takai','State' => 'Kano']);
State::create(['LGA' =>'Takum','State' => 'Taraba']);
State::create(['LGA' =>'Talata Mafara','State' => 'Zamfara']);
State::create(['LGA' =>'Tambuwal','State' => 'Sokoto']);
State::create(['LGA' =>'Tangaza','State' => 'Sokoto']);
State::create(['LGA' =>'Tarauni','State' => 'Kano']);
State::create(['LGA' =>'Tarka','State' => 'Benue']);
State::create(['LGA' =>'Tarmuwa','State' => 'Yobe']);
State::create(['LGA' =>'Taura','State' => 'Jigawa']);
State::create(['LGA' =>'Toungo','State' => 'Adamawa']);
State::create(['LGA' =>'Tofa','State' => 'Kano']);
State::create(['LGA' =>'Toro','State' => 'Bauchi']);
State::create(['LGA' =>'Toto','State' => 'Nasarawa']);
State::create(['LGA' =>'Chafe','State' => 'Zamfara']);
State::create(['LGA' =>'Tsanyawa','State' => 'Kano']);
State::create(['LGA' =>'Tudun Wada','State' => 'Kano']);
State::create(['LGA' =>'Tureta','State' => 'Sokoto']);
State::create(['LGA' =>'Udenu','State' => 'Enugu']);
State::create(['LGA' =>'Udi','State' => 'Enugu']);
State::create(['LGA' =>'Udu','State' => 'Delta']);
State::create(['LGA' =>'Udung-Uko','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ughelli North','State' => 'Delta']);
State::create(['LGA' =>'Ughelli South','State' => 'Delta']);
State::create(['LGA' =>'Ugwunagbo','State' => 'Abia']);
State::create(['LGA' =>'Uhunmwonde','State' => 'Edo']);
State::create(['LGA' =>'Ukanafun','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ukum','State' => 'Benue']);
State::create(['LGA' =>'Ukwa East','State' => 'Abia']);
State::create(['LGA' =>'Ukwa West','State' => 'Abia']);
State::create(['LGA' =>'Ukwuani','State' => 'Delta']);
State::create(['LGA' =>'Umuahia North','State' => 'Abia']);
State::create(['LGA' =>'Umuahia South','State' => 'Abia']);
State::create(['LGA' =>'Umu Nneochi','State' => 'Abia']);
State::create(['LGA' =>'Ungogo','State' => 'Kano']);
State::create(['LGA' =>'Unuimo','State' => 'Imo']);
State::create(['LGA' =>'Uruan','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Urue-Offong/Oruko','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Ushongo','State' => 'Benue']);
State::create(['LGA' =>'Ussa','State' => 'Taraba']);
State::create(['LGA' =>'Uvwie','State' => 'Delta']);
State::create(['LGA' =>'Uyo','State' => 'Akwa Ibom']);
State::create(['LGA' =>'Uzo Uwani','State' => 'Enugu']);
State::create(['LGA' =>'Vandeikya','State' => 'Benue']);
State::create(['LGA' =>'Wamako','State' => 'Sokoto']);
State::create(['LGA' =>'Wamba','State' => 'Nasarawa']);
State::create(['LGA' =>'Warawa','State' => 'Kano']);
State::create(['LGA' =>'Warji','State' => 'Bauchi']);
State::create(['LGA' =>'Warri North','State' => 'Delta']);
State::create(['LGA' =>'Warri South','State' => 'Delta']);
State::create(['LGA' =>'Warri South West','State' => 'Delta']);
State::create(['LGA' =>'Wasagu/Danko','State' => 'Kebbi']);
State::create(['LGA' =>'Wase','State' => 'Plateau']);
State::create(['LGA' =>'Wudil','State' => 'Kano']);
State::create(['LGA' =>'Wukari','State' => 'Taraba']);
State::create(['LGA' =>'Wurno','State' => 'Sokoto']);
State::create(['LGA' =>'Wushishi','State' => 'Niger']);
State::create(['LGA' =>'Yabo','State' => 'Sokoto']);
State::create(['LGA' =>'Yagba East','State' => 'Kogi']);
State::create(['LGA' =>'Yagba West','State' => 'Kogi']);
State::create(['LGA' =>'Yakuur','State' => 'Cross River']);
State::create(['LGA' =>'Yala','State' => 'Cross River']);
State::create(['LGA' =>'Yamaltu/Deba','State' => 'Gombe']);
State::create(['LGA' =>'Yankwashi','State' => 'Jigawa']);
State::create(['LGA' =>'Yauri','State' => 'Kebbi']);
State::create(['LGA' =>'Yenagoa','State' => 'Bayelsa']);
State::create(['LGA' =>'Yola North','State' => 'Adamawa']);
State::create(['LGA' =>'Yola South','State' => 'Adamawa']);
State::create(['LGA' =>'Yorro','State' => 'Taraba']);
State::create(['LGA' =>'Yunusari','State' => 'Yobe']);
State::create(['LGA' =>'Yusufari','State' => 'Yobe']);
State::create(['LGA' =>'Zaki','State' => 'Bauchi']);
State::create(['LGA' =>'Zango','State' => 'Katsina']);
State::create(['LGA' =>'Zangon Kataf','State' => 'Kaduna']);
State::create(['LGA' =>'Zaria','State' => 'Kaduna']);
State::create(['LGA' =>'Zing','State' => 'Taraba']);
State::create(['LGA' =>'Zurmi','State' => 'Zamfara']);
State::create(['LGA' =>'Zuru','State' => 'Kebbi']);

    }
}
